name: "CI Build"
description: "Run CI commands"
inputs:
  npm-command:
    default: "lint"
    description: "npm script to run"
    required: true
  tag:
    default: "latest"
    description: "Picidae-ci tag to use for action"
    required: true
runs:
  using: "docker"
  image: "ghcr.io/devcon4/picidae-ci:latest"
  args:
    - ${{inputs.npm-command}}
