FROM node:latest as Build

COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json

RUN cd /app; npm ci

COPY . /app

RUN cd /app; npm run build

FROM nginxinc/nginx-unprivileged:alpine as Runtime

RUN addgroup -S picidaegroup \
  && adduser -S picidaeuser -G picidaegroup

RUN mkdir /app \
  && chown -R picidaeuser /app

USER picidaeuser

COPY --from=Build /app/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=Build /app/dist/Picidae /usr/share/nginx/html

EXPOSE 80