FROM node:alpine as Build
# Context will be root dir not /client because of github action weirdness
# https://github.com/moby/buildkit/issues/1684

# RUN addgroup -S picidaegroup \
#   && adduser -S picidaeuser -G picidaegroup

# RUN mkdir /app \
#   && chown -R picidaeuser /app

# USER picidaeuser

COPY ./client/package.json /app/package.json
COPY ./client/package-lock.json /app/package-lock.json

RUN cd /app; npm ci

COPY ./client /app

RUN cd /app; npm run build

FROM nginx:alpine as Runtime

COPY --from=Build /app/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=Build /app/dist/Picidae /usr/share/nginx/html

EXPOSE 80