name: Publish Docker image
on:
  push:
    branches:
      - master
jobs:
  get_semver:
    name: Create semver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
  build_and_push_docker:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    needs: get_semver
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: /client
        pull: true
        push: true
        cache-from: type=registry,ref=devcon4/picidae:latest
        cache-to: type=inline
        tags: devcon4/picidae:${{ needs.get_semver.outputs.semVer }} latest
  create_tag:
    name: Push github tag
    runs-on: ubuntu-latest
    needs: 
      - get_semver
      - build_and_push_docker
    steps:
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ needs.get_semver.outputs.semVer }}",
              sha: context.sha
            })
