name: Pull Request Checks
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build dockerfile
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./client/dockerfile.ci
          load: true
          tags: picidae-ci:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          # outputs: type=docker,dest=/tmp/picidae-latest.tar
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: picidae-latest
      #     path: /tmp/picidae-latest.tar
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Load dockerfile
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./client/dockerfile.ci
          load: true
          tags: picidae-ci:latest
          cache-from: type=local,src=/tmp/.buildx-cache
      - name: Lint
        run: docker run picidae-ci:latest lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Load dockerfile
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./client/dockerfile.ci
          load: true
          tags: picidae-ci:latest
          cache-from: type=local,src=/tmp/.buildx-cache
      # - name: Download artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: picidae-latest
      #     path: /tmp
      # - name: Load Docker image
      #   run: |
      #     docker load --input /tmp/picidae-latest.tar
      #     docker image ls -a
      - name: Test
        run: docker run picidae-ci:latest test-ci
