name: Pull Request Checks
on:
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  get_semver:
    name: Create semver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
      nuGetVersionV2: ${{ steps.gitversion.outputs.NuGetVersionV2 }}
      escapedBranchName: ${{ steps.gitversion.outputs.EscapedBranchName }}
  build_and_push_dockerfile_ci:
    name: Push/build the ci dockerfile
    runs-on: ubuntu-latest
    needs: get_semver
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - name: Logout
        run: docker logout
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/dockerfile.ci
          pull: true
          push: true
          cache-from: type=registry,ref=ghcr.io/devcon4/picidae-ci:${{ needs.get_semver.outputs.escapedBranchName }}
          cache-to: type=inline
          tags: |
            ghcr.io/devcon4/picidae-ci:${{ needs.get_semver.outputs.escapedBranchName }}
            ghcr.io/devcon4/picidae-ci:${{ needs.get_semver.outputs.nuGetVersionV2 }}
  run_lint:
    name: Lint angular client
    runs-on: ubuntu-latest
    needs: build_and_push_dockerfile_ci
    container:
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      image: ghcr.io/devcon4/picidae-ci:${{ needs.get_semver.outputs.nuGetVersionV2 }}
    steps:
      - name: Run lint
        run: cd /app && npm run lint
      - name: Run test
        run: cd /app && npm run test-ci
