name: Pull Request Checks
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  ci_tasks:
    name: build the ci dockerfile and run checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build dockerfile
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./client/dockerfile.ci
          load: true
          tags: picidae-ci:latest
      - name: Lint
        run: docker run picidae-ci:latest lint
