name: Checks
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  build:
    name: Build CI Image
    runs-on: ubuntu-latest
    steps:
      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache-layers
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Cache Docker image
        uses: actions/cache@v2
        with:
          path: /tmp/picidae-latest.tar
          key: ${{ runner.os }}-picidae-latest-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-picidae-latest-
      - name: Checkout code
        if: steps.cache-layers.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        if: steps.cache-layers.outputs.cache-hit != 'true'
        uses: docker/setup-buildx-action@v1
      - name: Build dockerfile
        if: steps.cache-layers.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./client/dockerfile.ci
          load: true
          tags: picidae-ci:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          outputs: type=docker,dest=/tmp/picidae-latest-new.tar
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move buildx cache
        if: steps.cache-layers.outputs.cache-hit != 'true'
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move image cache
        if: steps.cache-layers.outputs.cache-hit != 'true'
        run: |
          rm -rf /tmp/picidae-latest.tar
          mv /tmp/picidae-latest-new.tar /tmp/picidae-latest.tar
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    steps:
      - name: Cache Docker image
        uses: actions/cache@v2
        with:
          path: /tmp/picidae-latest.tar
          key: ${{ runner.os }}-picidae-latest-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-picidae-latest-
      - name: Load Docker image
        run: |
          docker load --input /tmp/picidae-latest.tar
          docker image ls -a
      - name: Lint
        run: docker run picidae-ci:latest lint
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    steps:
      - name: Cache Docker image
        uses: actions/cache@v2
        with:
          path: /tmp/picidae-latest.tar
          key: ${{ runner.os }}-picidae-latest-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-picidae-latest-
      - name: Load Docker image
        run: |
          docker load --input /tmp/picidae-latest.tar
          docker image ls -a
      - name: Test
        run: docker run picidae-ci:latest test-ci
